/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 laptop.gltf --transform 
Files: laptop.gltf [2.8MB] > C:\Users\Abhishek Kank\Desktop\laptop\laptop-transformed.glb [1.12MB] (60%)
Author: yakuphan (https://sketchfab.com/yakuphan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/laptop-ed2a53dd243f492b8ce3ad1f4f54457b
Title: Laptop
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/laptop-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.918}>
          <group name="pCylinder3" position={[1.654, 0.192, -1.15]} rotation={[-Math.PI / 9, 0, Math.PI / 2]} scale={[0.075, 0.15, 0.075]}>
            <group name="pCube134" position={[17.195, 11.027, -2.966]} rotation={[0, 0.14, -Math.PI / 2]} scale={[23, 26, 0.133]}>
              <mesh name="pCube134_blinn1_0" geometry={nodes.pCube134_blinn1_0.geometry} material={materials.blinn1} />
            </group>
            <group name="pCylinder2" position={[0, 22.053, 0]}>
              <mesh name="pCylinder2_phong1_0" geometry={nodes.pCylinder2_phong1_0.geometry} material={materials.phong1} />
            </group>
            <group name="pCube4" position={[15.072, 11.027, -2.725]} rotation={[0, -1.431, -Math.PI / 2]} scale={[24, 0.667, 32]}>
              <mesh name="pCube4_phong1_0" geometry={nodes.pCube4_phong1_0.geometry} material={materials.phong1} />
            </group>
            <mesh name="pCylinder3_phong1_0" geometry={nodes.pCylinder3_phong1_0.geometry} material={materials.phong1} />
          </group>
        </group>
        <mesh name="pCylinder1_phong1_0" geometry={nodes.pCylinder1_phong1_0.geometry} material={materials.phong1} position={[0, 0.176, -1.055]} rotation={[-0.384, 0, Math.PI / 2]} scale={[0.069, 1.376, 0.069]} />
        <mesh name="pCube6_lambert1_0" geometry={nodes.pCube6_lambert1_0.geometry} material={materials.lambert1} position={[-1.599, 0.138, 0.335]} scale={[0.092, 0.009, 0.073]} />
        <mesh name="pCube7_phong3_0" geometry={nodes.pCube7_phong3_0.geometry} material={materials.phong3} position={[1.599, 0.138, 0.335]} scale={[0.092, 0.009, 0.073]} />
        <mesh name="pCube3_phong2_0" geometry={nodes.pCube3_phong2_0.geometry} material={materials.phong2} position={[-1.487, 0.17, -0.578]} scale={[0.092, 0.046, 0.069]} />
        <mesh name="pCube135_phong4_0" geometry={nodes.pCube135_phong4_0.geometry} material={materials.phong4} position={[0, 0.179, 0.702]} scale={[0.642, 0.001, 0.367]} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
